### ISSUE TITLE
`tr.reset_identity()` does not work properly

### ISSUE THREAD

**Issue by shivam6294** [erdiaker/torrequest#1]
`tr.reset_identity()` does not seem to work properly. I'm using python 3.6 and Tor version 0.2.7.6 (git-605ae665009853bd).

Are there any additional settings that I may have to change in the Tor config or something? If so then that should be added to the readme

**Comment by Lauchturm** [comment]
works like that for me:
with TorRequest(proxy_port=9050, ctrl_port=9051, password='YOURtorpwdhere') as tr:
  response = tr.get('http://ipecho.net/plain')
  print(response.text)  # not your IP address

  tr.reset_identity()

  response = tr.get('http://ipecho.net/plain')
  print(response.text)

also needs to have hashpwd and controlport enabled in torrc

**Comment by alanmarazzi** [comment]
Hi, I have set the torrc correctly and in fact tor service is giving me: 
```
Apr 27 16:38:09.000 [notice] New control connection opened from 127.0.0.1.
```
Anyway `reset_identity()` is not working, or at least not as expected:
```
{
  "origin": "81.119.xx.xx"
}

{
  "origin": "81.119.xx.xx"
}
```
Furthermore that is my IP, so it looks like I'm not even piping the request to Tor...
