### ISSUE TITLE
trouble with https

### ISSUE THREAD

**Issue by ZombieCait** [erdiaker/torrequest#8]
IP doesn't change when url with **https**. What can I do with this?

**Comment by cverluise** [comment]
Hello, 

don't use the pip distribution. 
Clone the repo and make sure you are on the latest commit (#2ad9b57e481afd5a7a5) which specifically addressed this issue. 

Hope it helps,

Best

**Comment by VitaliiVlo** [comment]
+1 , library in pip have some type in the code. 
instead of "https" we have "https:"
